apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xulbsc0xz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xulbsc0xz-python 
  name: xulbsc0xz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xulbsc0xz-python 
